### ISSUE TITLE
一直账号密码错误

### ISSUE THREAD

**Issue by gittkt** [Mask0913/Ayit_library#2]
试了好几个一直显示账号密码错误，运行时好像还报错了
D:\control\login.py:35: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(peopleId) is 0 or len(peoplePassword) is 0:
D:\control\login.py:35: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(peopleId) is 0 or len(peoplePassword) is 0:

**Comment by Mask0913** [comment]
账号密码是根据C盘卷标生成的

**Comment by Mask0913** [comment]
def get_key(self, account):
        account = int(account) * 8 - 15 + 50 * 18 / 30
        account = str(account)
        account = bytes(account, encoding='utf8')
        key = base64.encodestring(account)
        key = str(key, encoding='utf-8')
        return key

**Comment by Mask0913** [comment]
这个函数   account 是卷标  password是根据这个函数生成的

**Comment by Mask0913** [comment]
当然 ，你也可以使用 python ai_lib.py 直接启动main界面

**Comment by gittkt** [comment]
> 账号密码是根据C盘卷标生成的
只生成了账号密码还是空白
![292CB438-5E1E-4839-81C4-6D25152843AD](https://user-images.githubusercontent.com/90975942/133915495-ff6c23c1-a14c-4bab-a6e1-16bb2163a7e1.png)

**Comment by gittkt** [comment]
> 当然 ，你也可以使用 python ai_lib.py 直接启动main界面

这个方法到启动userdata那个文件那一步出问题了，那个文件也在这个目录下，也能打开
![C3BE9434-DAA7-4218-9C6A-B7E17F95A0C8](https://user-images.githubusercontent.com/90975942/133915509-991ec3b2-c013-4980-9cfc-236eb95114b5.png)

**Comment by gittkt** [comment]
> > 当然 ，你也可以使用 python ai_lib.py 直接启动main界面
> 
> 这个方法到启动userdata那个文件那一步出问题了，那个文件也在这个目录下，也能打开
> ![C3BE9434-DAA7-4218-9C6A-B7E17F95A0C8](https://user-images.githubusercontent.com/90975942/133915509-991ec3b2-c013-4980-9cfc-236eb95114b5.png)

Traceback (most recent call last):
  File "C:\control\ai_lib.py", line 407, in <module>
    mainWindow = auto_win()
  File "C:\control\ai_lib.py", line 138, in __init__
    self.get_user_data()
  File "C:\control\ai_lib.py", line 236, in get_user_data
    f = open('user_data.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'user_data.txt'

> > 当然 ，你也可以使用 python ai_lib.py 直接启动main界面
> 
> 这个方法到启动userdata那个文件那一步出问题了，那个文件也在这个目录下，也能打开
> ![C3BE9434-DAA7-4218-9C6A-B7E17F95A0C8](https://user-images.githubusercontent.com/90975942/133915509-991ec3b2-c013-4980-9cfc-236eb95114b5.png)

这个是提示的信息Traceback (most recent call last):
  File "C:\control\ai_lib.py", line 407, in <module>
    mainWindow = auto_win()
  File "C:\control\ai_lib.py", line 138, in __init__
    self.get_user_data()
  File "C:\control\ai_lib.py", line 236, in get_user_data
    f = open('user_data.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'user_data.txt'

**Comment by Mask0913** [comment]
> > > 当然 ，你也可以使用 python ai_lib.py 直接启动main界面
> > 
> > 
> > 这个方法到启动userdata那个文件那一步出问题了，那个文件也在这个目录下，也能打开
> > ![C3BE9434-DAA7-4218-9C6A-B7E17F95A0C8](https://user-images.githubusercontent.com/90975942/133915509-991ec3b2-c013-4980-9cfc-236eb95114b5.png)
> 
> Traceback (most recent call last): File "C:\control\ai_lib.py", line 407, in mainWindow = auto_win() File "C:\control\ai_lib.py", line 138, in **init** self.get_user_data() File "C:\control\ai_lib.py", line 236, in get_user_data f = open('user_data.txt', 'r') FileNotFoundError: [Errno 2] No such file or directory: 'user_data.txt'
> 
> > > 当然 ，你也可以使用 python ai_lib.py 直接启动main界面
> > 
> > 
> > 这个方法到启动userdata那个文件那一步出问题了，那个文件也在这个目录下，也能打开
> > ![C3BE9434-DAA7-4218-9C6A-B7E17F95A0C8](https://user-images.githubusercontent.com/90975942/133915509-991ec3b2-c013-4980-9cfc-236eb95114b5.png)
> 
> 这个是提示的信息Traceback (most recent call last): File "C:\control\ai_lib.py", line 407, in mainWindow = auto_win() File "C:\control\ai_lib.py", line 138, in **init** self.get_user_data() File "C:\control\ai_lib.py", line 236, in get_user_data f = open('user_data.txt', 'r') FileNotFoundError: [Errno 2] No such file or directory: 'user_data.txt'

 抱歉 这个我也不清楚  ，可能这个与你 配置的python环境相关
