### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by 0Triste** [Mask0913/Ayit_library#8]
打包完成后报错
Traceback (most recent call last):
  File "ai_lib.py", line 486, in <module>
  File "ai_lib.py", line 261, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'cookie.txt'
正常运行ai_lib.py可以正常使用

**Comment by 0Triste** [comment]
把四个txt文本放入exe文件的同一路径内解决了

**Comment by Mask0913** [comment]
好的 谢谢！
